name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: cache
        # just cache on the main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Cache import
        if: ${{ steps.cache.outputs.cache-hit == true }}
        run: ./.github/cache_import.sh

      - name: Cache import test
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          ./.github/cache_import.sh
          echo ${{ steps.cache.outputs.cache-hit }}

      - name: Build
        run: ./mbs.sh build run --verbose --sandbox

      - name: Cache export
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./.github/cache_export.sh
